title: Lam T Nguyen
author: Lam T Nguyen
subtitle: MS in Computer Science

google_analytics: G-ZEFRYNXSX4

url:
baseurl:

footer_url:
footer_text: "Copyright Â© 2025 Lam T Nguyen"

profile-picture: assets/profile.jpg
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "cv"
   link: ""
#  - name: "blog"
  #  link: "/blog"
 - name: "github"
   link: "https://github.com/lamng3"
 - name: "open review"
   link: "https://openreview.net/profile?id=~Lam_T_Nguyen1"

markdown: kramdown
kramdown:
  math_engine: katex
